model:
    arch: danet_50
data:
    dataset: pascal
    train_split: train_aug
    val_split: val
    img_rows: 'same'
    img_cols: 'same'
    path: /mnt/DATA/VOC/VOCdevkit/VOC2012
training:
    train_iters: 1459950
    batch_size: 2
    val_interval: 100
    print_interval: 50
    n_workers: 16
    optimizer:
        name: 'sgd'
        lr: 1.0e-4
        weight_decay: 0.0005
        momentum: 0.9
    lr_schedule:
    loss:
      name: 'cross_entropy'
      size_average: False
    # l_rate: 1.0e-4
    # l_schedule:
    # momentum: 0.99
    # weight_decay: 0.0005
    resume: danet_pascal_voc_best_model.pkl
    ckpt_path: checkpoints/
    visdom: False
